name: cs5670_python_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.8.0
  - numpy=1.21.5
  - opencv=4.6.0
  - pillow=10.0.1
  - py-opencv=4.6.0
  - pyparsing=3.0.9
  - python=3.9
  - pyttk=0.3.2
  - scipy=1.7.3
  - tk=8.6.12
  - nose=1.3.7
  - imageio=2.8.0

